### ISSUE TITLE
Early drop of mutex guard

### ISSUE THREAD

**Issue by wangrunji0408** [skyzh/rust-ycsb#1]
https://github.com/skyzh/rust-ycsb/blob/b1741cfe5f602d3bbbaf7c6f26e0a69ab06ec054/src/generator/acknowledged_counter_generator.rs#L39

The `MutexGuard` will be dropped after this line, then a race condition will happen in the following block.

It can be fixed by:

```rust
if let Ok(_guard) = self.core.try_lock() { 
```

**Comment by skyzh** [comment]
Thanks for pointing that out!
